name: Check Build

on:
  push:
    branches: [main]
    paths:
      - 'src/*'
      - 'img/*'
      - 'fonts/*'
      - '.github/workflows/check.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/*'
      - 'img/*'
      - 'fonts/*'
      - '.github/workflows/check.yml'
  workflow_dispatch:

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: check build
        run: |
          apt-get update && apt-get install -y libfuse2
          tectonic -X build
